apiVersion: troubleshoot.replicated.com/v1beta1
kind: Preflight
metadata:
  name: example-preflight-checks
spec:
  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.13.0"
              message: The application requires at Kubernetes 1.13.0 or later, and recommends 1.15.0.
              uri: https://www.kubernetes.io
          - warn:
              when: "< 1.15.0"
              message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.15.0 or later.
              uri: https://kubernetes.io
          - pass:
              when: ">= 1.15.0"
              message: Your cluster meets the recommended and required versions of Kubernetes.
    - distribution:
        outcomes:
          - fail:
              when: "= dockerdesktop"
              message: "Docker desktop is not supported."
          - pass:
              when: "= gke"
              message: "GKE is a fully supported distribution."
          - pass:
              when: "= eks"
              message: "EKS is a fully supported distribution."
          - warn:
              message: "This is not a fully supported Kubernetes distribution."
    - storageClass:
        checkName: Required storage classes
        storageClassName: "standard"
        outcomes:
          - warn:
              message: This cluster is using an unsupported storage class.
          - pass:
              message: The current cluster's storage class is fully supported.
    - containerRuntime:
        outcomes:
          - fail:
              when: "== gvisor"
              message: The application does not support gvisor.
          - pass:
              message: A supported container runtime was found.
    - customResourceDefinition:
        customResourceDefinitionName: constrainttemplates.templates.gatekeeper.sh
        checkName: Gatekeeper policy runtime
        outcomes:
          - fail:
              message: Gatekeeper is required for the application, but not found in the cluster.
              uri: https://enterprise.support.io/installing/gatekeeper
          - pass:
              message: Found a supported version of Gatekeeper installed and running in the cluster.
    - imagePullSecret:
        checkName: Registry credentials for Quay.io
        registryName: quay.io
        outcomes:
          - fail:
              message: |
                Cannot pull from quay.io. An image pull secret should be deployed to the cluster that has credentials to pull the images. To obtain this secret, please contact your support rep.
              uri: https://enterprise.support.io/installing/registry-credentials
          - pass:
              message: Found credentials to pull from quay.io
